### ISSUE TITLE
2sxc FAQ App Interferes with Oqtane Navigation

### ISSUE THREAD

**Issue by tvatavuk** [2sic/app-faq#26]
**Description:**

When using the 2sxc FAQ app inside Oqtane, there seems to be a conflict in the navigation behavior. The attribute `data-bs-target` is utilized by the FAQ app as an element selector to add a click event. However, this selector is not specific enough. As a result, it inadvertently selects multiple navigation elements in the default Oqtane theme. This changes the click behavior of these navigation elements, leading to a broken navigation experience on the Oqtane site, after page with FAQ app is visited.

**Steps to Reproduce:**
1. Install the 2sxc FAQ app in Oqtane site and add it to FAQ page.
2. Navigate to the FAQ page.
3. Try navigating using the default Oqtane theme's navigation elements to some other page. It will not work.

![slika](https://github.com/2sic/app-faq/assets/2724850/40bca506-9391-4e9f-be37-5a5e91c13ade)

**Expected Behavior:**
The Oqtane navigation should function as intended, regardless of interactions with the FAQ app.

**Actual Behavior:**
The navigation on the Oqtane site breaks after page with FAQ app is browsed.

**Possible Solution:**
A potential fix could be to use a more specific attribute for the FAQ app, such as `data-bs-target-faq`, to prevent any unintended interference with Oqtane's navigation elements.

**Comment by ropalko** [comment]
Created a new release [v04.06.00](https://github.com/2sic/app-faq/releases/tag/v04.06.00)
